### ISSUE TITLE
YWC Intranet: JS error on lazy loading assets when editing existing post

### ISSUE THREAD

**Issue by topherwhite** [ywc/ywc#2]
It works when using "add item", but not for edit. Suspected escaping issue with loading existing content.

**Comment by topherwhite** [comment]
Bug seems to be tied to lines 151-157 in ywc-input-text.xsl, where the existing value is loaded as Javscript string. The error might be related to "exotic" whitespace characters. Still investigating...

**Comment by micheal-cooper** [comment]
I tested the theory that the Javascript was loading when you click Create but not when you click Edit. However, even after clicking Create, I was not able to Edit.
Private vid to Topher: https://www.youtube.com/watch?v=CyDh3cdkLpU

**Comment by micheal-cooper** [comment]
Closed by mistake. Wanted to check on progress.

**Comment by micheal-cooper** [comment]
Our webdev Francesc sent me a detailed error report:

I want to edit my post in tida and change the link (http://en.wikipedia.org/wiki/St._George%27s_Day#Catalonia that was the one!), but no luck :(,
the javascript fails:
Timestamp: 23/04/2013 11:26:03
Error: SyntaxError: unterminated string literal
Source File: https://tida.oist.jp/inc/js?inc=jquery,aaaaac,1.7.2;ywc-core,aaaaba,1.0;oist-core,bbbbbb,1.0;
Line: 4, Column: 52
Source Code:
$(function(){YWC.input.value.text["community-body"]="<p>

**Comment by topherwhite** [comment]
This bug has been fixed, and was most likely tied to deprecated version of CKEditor (also some exotic UTF characters).
