### ISSUE TITLE
Upcoming Events timezone is off

### ISSUE THREAD

**Issue by micheal-cooper** [ywc/ywc#8]
In the Upcoming Events block, the time is shown in GMT rather than the local timezone JST (GMT+9). 

Please look at the screenshot:
![screen shot 2014-02-06 at 16 48 18](https://f.cloud.github.com/assets/3095809/2096375/4abec0b4-8f03-11e3-9294-05cc9d9828f6.jpg)

**Comment by micheal-cooper** [comment]
In the past week, two users asked me about this problem, and a third just approached me in the hall. She let me check her client, and both OS and browser have the correct timezone, JST. So let's get this patched soon. Thanks.

**Comment by micheal-cooper** [comment]
I have figured out the pattern. Chrome is showing the time of the events in GMT while Firefox is showing them in the timezone of the user's client. Maybe YWC is failing to get the client timezone from Chrome?
![screen shot 2014-04-18 at 16 25 31](https://cloud.githubusercontent.com/assets/3095809/2740217/223fef86-c6cc-11e3-95ea-4ee10761d306.jpg)

**Comment by micheal-cooper** [comment]
Before, you said this was an easy fix and that you understood what was wrong, so if you can fix this easy and quick, that would be great.

**Comment by micheal-cooper** [comment]
Additional detail:

When you click the Event on the TIDA Top to get the details popup, it only shows the time if there is an explicit End Time. The End Time on Events is optional, so TIDA needs to show the Start Time and the End Time IF there is one, but always the Start Time.

**Comment by topherwhite** [comment]
@micheal-cooper, thanks for all the support on narrowing this down. I should be fixed now. If it is fixed on tidafe2, please close the issue (I won't close it til you confirm). Thanks!

**Comment by micheal-cooper** [comment]
I have confirmed this on Mac Chrome, Mac FF, and Win7JA IE11. It is done. Thank you very much.
